### ISSUE TITLE
Peer to peer code review - Hummingbird.

### ISSUE THREAD

**Issue by xtrmdarc** [nriqu322/using-bootstrap#1]
- Use pl-5 in the container to make it more centered.
- Use pointer: cursor for the articles section or a tag.
- Really good project. 
- Fix the header in mobile resolution.
- Adjust the widths of the article in the magazine section.
- Fix heights in the newsletter-subscribe section.
- Good use of bootstrap classes.
- Nice work.

**Comment by nriqu322** [comment]
Thank you for your review. All comments implemented.
